### ISSUE TITLE
"load template from file" not working

### ISSUE THREAD

**Issue by maxdamage667** [ricrogz/MultiTemplateLoader#1]
Hey,

"load template from a file" doesn't work. It opens an empty composer with the html templates that I've used so far. If I include these templates into the list as, say, template 1, it works.

Thanks for continuing this addon. (Even though thunderbird seems to become deprecated more and more)

This is one of the files that I used for testing:
[20170531-PM des SFR e.V._ Schule_ Nicht für Alle!-1031-3.html.zip](https://github.com/ricrogz/MultiTemplateLoader/files/1040701/20170531-PM.des.SFR.e.V._.Schule_.Nicht.fur.Alle.-1031-3.html.zip)

**Comment by ricrogz** [comment]
Hallo @maxdamage667 !

(mein Deutsch ist nicht mehr so gut, also besser schreibe Ich auf English ;-) )

Thank you very much for reporting the bug. It has been a long time since I last had a look at this code, but I have attempted to implement a quick fix for the problem. I think it works, and I hope it does not break anything else.

I just pushed the fixed code, submitted a new version of the extension to Mozilla, I hope they will accept it soon.
